# Build and publish a release of OpenGamepadUI using semantic-release whenever
# changes are merged into main.
name: "Release"

on:
  push:
    branches:
      - main
      - v0.x
      - v1.x
    paths-ignore:
      - README.md
      - "docs/**"

env:
  IMAGE_NAME: ghcr.io/shadowblip/opengamepadui-builder

# Jobs to run
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install @semantic-release/exec @google/semantic-release-replace-plugin @semantic-release/git

      - name: Save the signing key to sign update packs
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" > assets/crypto/keys/opengamepadui.key

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release

      - name: Trigger documentation generation
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H 'Authorization: Bearer ${{ secrets.DISPATCH_KEY }}' \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ShadowBlip/OpenGamepadUI/dispatches \
            --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
